### ISSUE TITLE
Permalinks and via distbin-html links not working

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/distbin_ynh#20]
they go to localhost instead of the public url
from @kabitk

**Comment by kabitk** [comment]
The Permalink goes to localhost; also "fetched from"; although that is not a problem, it should be changed to rather show the domain.

**Comment by yalh76** [comment]
can you test it after upgrading with:
`yunohost app upgrade distbin -u https://github.com/YunoHost-Apps/distbin_ynh/tree/testing --debug`
and let me know if all work now

**Comment by yalh76** [comment]
After some test, I push the fix on production.
