### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/distbin_ynh#70]
### Describe the bug
**504 Gateway Time-out**
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
i add NODE_OPTIONS="--max-old-space-size=128" to /var/www/distbin/.env to reduce max memory reservation it improve responsivity but i obtain a :
**502 Bad Gateway** and same error heap out of memory

### Context

- Hardware: odroid hc1 armhf(v7) 2Gb RAM 
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: **inside lxc container** btrfs and no swapis possible to configure.
- Using, or trying to install package version/branch: master
- If upgrading, current package version: NA

### Steps to reproduce

- after install 
- open wel the distbin page
- then or
  - paste a big text 800kb
  - then publish
- or
  - clic public 

### Expected behavior

To much default memory consumption just to share 1meg text file.
i would just that it works on 2gb memory server :P
### Logs

https://paste.yunohost.org/udojuqebuf

**Comment by yalh76** [comment]
it not an issue from this package or from distbin, seems more an issue from nodejs eating too much ram and from your lxc that require more RAM or adding a swap file

if you are looking for an app to share a 1meg text file, maybe distbin is not the good app for that, distbin is more a pastebin dedicated working with activity pub.

You should look at https://github.com/YunoHost-Apps/haste_ynh or https://github.com/YunoHost-Apps/privatebin_ynh
